language: node_js

node_js:
  - 'node'
  - 'lts/*'

cache:
  directories:
    - ~/.npm
    - node_modules

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
